# Generated by Django 4.2.2 on 2023-06-25 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_vacancy_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='review',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
