# Generated by Django 4.2.2 on 2023-07-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_founding_date_company_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full', 'full_time'), ('part', 'part_time'), ('comp', 'completed_work')], default='full', max_length=4),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skill_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy')),
            ],
        ),
    ]
