# Generated by Django 4.2.2 on 2023-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vacancy_employment_type_vacancy_skill_name_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
