# Generated by Django 4.2.2 on 2023-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('expected_salary', models.SmallIntegerField()),
                ('is_searching', models.BooleanField(default=True, verbose_name='Ищет работу?')),
            ],
        ),
    ]
